name: Go CI

on:
  push:
    branches:
      - master # Run workflow on push to the `master` branch
  pull_request:
    branches:
      - master # Run workflow on pull requests to the `master` branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Check out the repository code

      - name: Set up Go
        uses: actions/setup-go@v4 # Set up Go environment
        with:
          go-version: 1.23.5 # Specify the Go version (adjust as needed)

      - name: Install Dependencies
        run: go mod tidy # Ensure dependencies are up to date

      - name: Run Tests
        run: go test ./... -v # Run all tests with verbose output

      - name: Lint Code
        run: go vet ./... # Perform static analysis on Go code

      - name: Build Application
        run: go build -o sharex-upload-server ./cmd/server # Build the server binary
